# -*- coding: utf-8 -*-
"""Visualising Streaming Data with Streamlit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16x1pWIGPpl0z7mprhGg2d2n5_Ya5tCVq

**Visualising Streaming Data with Streamlit**
This project aims to create a real-time data visualization dashboard using Streamlit. The goal is to analyze streaming data from Reddit and identify instances of fraud in the telecommunications industry. By connecting to Reddit's API, collecting real-time posts, processing the data, and visualizing it using Streamlit, we can gain insights into telecom fraud patterns.

**Problem Statement**
Fraud in the telecommunications sector poses a significant challenge, costing the industry billions of dollars annually. Fraudsters exploit weaknesses in telecom infrastructure, engaging in activities like phone system hacking, identity theft, and billing fraud. Detecting and preventing fraud in real-time is crucial to minimizing financial losses.

The task at hand is to develop a real-time data visualization dashboard that monitors Reddit for telecom fraud mentions. By leveraging keywords like "telecoms scam," "phone fraud," "billing fraud," and "identity theft," we can extract relevant information from posts, including the post text, user name, subreddit, and date/time. Analyzing this data will help identify patterns and trends associated with telecom fraud.

**Project Requirements**
To successfully complete this project, the following requirements must be met:

Connect to Reddit's API and retrieve real-time posts related to telecom fraud and related keywords.
Process the collected posts to extract key information, such as post text, user name, subreddit, and date/time.
Analyze the data to identify patterns and trends related to telecom fraud and the specified keywords.
Utilize the Streamlit framework to build an interactive data visualization dashboard.
Include at least one meaningful chart or graph in the dashboard, such as a bar chart displaying the number of fraud mentions by subreddit or a line chart showing the frequency of fraud mentions over time.
Ensure the dashboard is user-friendly, visually appealing, and provides clear instructions and labels.
"""

import praw
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

# Reddit API credentials
client_id = 'oPDNjFu3-ESF1x69AFensA'
client_secret = '7HaJWrWLI6ACj4fx3vqxu3kXWCcJow'
user_agent = 'egmoturi'

# Connect to Reddit API
reddit = praw.Reddit(client_id=client_id, client_secret=client_secret, user_agent=user_agent)

# Streamlit App
st.title("Telecom Fraud Visualization Dashboard")

# Function to collect recent posts
def collect_posts(keywords, limit=50):
    posts = []
    for keyword in keywords:
        subreddit = reddit.subreddit('all')
        subreddit_posts = subreddit.search(keyword, limit=limit)
        for post in subreddit_posts:
            posts.append([post.title, post.author.name, post.subreddit.display_name, post.created_utc])
    return posts

# Process the collected posts
def process_posts(posts):
    df = pd.DataFrame(posts, columns=['Title', 'Author', 'Subreddit', 'Timestamp'])
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], unit='s')
    return df

# Analyze the data and create visualizations
def analyze_data(df):
    st.subheader("Fraud Mentions by Subreddit")
    subreddit_counts = df['Subreddit'].value_counts().head(10)
    st.bar_chart(subreddit_counts)

    st.subheader("Fraud Mentions Over Time")
    daily_counts = df.set_index('Timestamp').resample('D').size()
    st.line_chart(daily_counts)

# Main function to run the Streamlit app
def main():
    keywords = ['telecoms fraud', 'telecoms scam', 'phone fraud', 'billing fraud', 'identity theft']
    posts = collect_posts(keywords)
    df = process_posts(posts)
    st.title("Telecom Fraud Posts")
    st.dataframe(df)
    analyze_data(df)

if __name__ == '__main__':
    main()